# BungeeUtils Configuration
defaultserver: hub

# Do you want us to change /server and add /listservers?
addlistservers: true

# Don't touch this line. Its for logging purposes
peakplayers: 0

# Don't tocuh this line. For storage purposes.
maintenancemode: true

messages:
    noperm: '&cPermission Denied'
    kickmaintenance: '&cYou have been kicked due to the server being in &bmaintenance &cmode. &aJoin back soon'

motd:
  maintenance: '&cServer currently in maintenance mode!                 &eCheck twitter
    for updates &b@ArkhamNetwork'
  unknownplayer: '&7&l-&9&l-&3&l-&b&l> &4&lArkham&6&lNetwork &e&l1.7.5 &b&l<&3&l-&9&l-&7&l-                  &e&l&nUPDATE&r&8&l:
    &a&oSkyWars &b&o2.0 &a&osoon &6& &41.7.6 &bSupport added.'
  player: '&7&l-&9&l-&3&l-&b&l> &4&lArkham&6&lNetwork &e&l1.7.5 &b&l<&3&l-&9&l-&7&l-
    &d[player]     &e&l&nUPDATE&r&8&l: &a&oSkyWars &b&o2.0 &a&osoon &6& &41.7.6 &bSupport
    added.'

tabcolor:
  default: YELLOW
  staff: LIGHT_PURPLE

hoverplayerlist:
- '&7&l-&9&l-&3&l-&b&l> &4&lArkham&6&lNetwork &e&l1.7.5 &b&l<&3&l-&9&l-&7&l-'
- ''
- '&6Players Online: &a[online]&c/&a[max]'
- '&6Highest Playercount: &a[peakplayers]&c/&a[max]'
- ''
- '&dWebsite: &ahttps://www.arkhamnetwork.org/'
- '&dForums: &ahttps://www.arkhamnetwork.org/community/'
- '&dStore: &ahttps://buy.arkhamnetwork.org/'
- '&dVote: &ahttps://www.arkhamnetwork.org/vote'
- '&dTokens: &ahttps://buy.arkhamnetwork.org/tokens'
- '&dCasino: &ahttps://buy.arkhamnetwork.org/casino'
hoverplayerlistmaintenance:
- '&cThe server is currently in &bmaintenance &cmode.'
- '&dWe will be back soon!'